### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by ned-kelly** [manio/skymax-demo#1]
For those interested, I've created a docker based Home Assistant automation of your Skymax fork and tested with  both Serial & USB -- It might be worth mentioning in your Readme for those looking to integrate with a Home Automation system: https://github.com/ned-kelly/docker-voltronic-homeassistant

Thanks for all your hard work figuring this one out!

@manio & @leithhobson

**Comment by manio** [comment]
Thanks! :)
