### ISSUE TITLE
tautology in main.cpp:getSettingsFile()

### ISSUE THREAD

**Issue by dilyanpalauzov** [manio/skymax-demo#10]
https://github.com/manio/skymax-demo/blob/master/main.cpp#L90 contains:
```c
                else if(linepart1 == "watt_factor")
                    attemptAddSetting(&wattfactor, linepart2);
                else if(linepart1 == "watt_factor")
                    attemptAddSetting(&wattfactor, linepart2);
                else
```
For me this is tautology: the second `else` will never match.

**Comment by manio** [comment]
Yes, you are totally right. In fact it is not even my code...
Will you create a PR or you wish I should fix it myself?

**Comment by dilyanpalauzov** [comment]
Please fix this.
