### ISSUE TITLE
Does now work with Voltronic Axpert King II

### ISSUE THREAD

**Issue by melnik-cto** [manio/skymax-demo#19]
Hello.
I have 4 inverters Voltronic Axpert King II with same problem. When I try to get statistics from him (never mind use usb or rs232, result the same) have next output:

> 
> ./inverter_poller -d -1
> Mon Jul 24 15:06:18 2023 INVERTER: Debug set
> Mon Jul 24 15:06:18 2023 INVERTER: Current CRC: 49 C1
> Mon Jul 24 15:06:18 2023 INVERTER: QMOD reply size (5 bytes)
> Mon Jul 24 15:06:18 2023 INVERTER: QMOD: 5 bytes read: (S
> Mon Jul 24 15:06:18 2023 INVERTER: QMOD query finished
> Mon Jul 24 15:06:18 2023 INVERTER: Current CRC: B7 A9
> Mon Jul 24 15:06:18 2023 INVERTER: QPIGS reply size (110 bytes)
> Mon Jul 24 15:06:18 2023 INVERTER: QPIGS: 110 bytes read: (238.1 49.9 000.0 00.0 0000 0000 000 001 00.10 000 000 0028 0000 000.0 00.00 00000 00000000 00 00 00000 000
> Mon Jul 24 15:06:18 2023 INVERTER: QPIGS query finished
> Mon Jul 24 15:06:18 2023 INVERTER: Current CRC: F8 54
> Mon Jul 24 15:06:19 2023 INVERTER: QPIRI reply size (97 bytes)
> Mon Jul 24 15:06:19 2023 INVERTER: QPIRI: incorrect start/stop bytes.  Buffer: (230.0 21.7 230.0 50.0 21.7 5000 5000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:19 2023 INVERTER: Current CRC: B4 DA
> Mon Jul 24 15:06:19 2023 INVERTER: QPIWS reply size (36 bytes)
> Mon Jul 24 15:06:19 2023 INVERTER: QPIWS: incorrect start/stop bytes.  Buffer: (100000000000001000000010000000010000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:24 2023 INVERTER: Current CRC: F8 54
> Mon Jul 24 15:06:24 2023 INVERTER: QPIRI reply size (97 bytes)
> Mon Jul 24 15:06:24 2023 INVERTER: QPIRI: incorrect start/stop bytes.  Buffer: (230.0 21.7 230.0 50.0 21.7 5000 5000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:24 2023 INVERTER: Current CRC: B4 DA
> Mon Jul 24 15:06:25 2023 INVERTER: QPIWS reply size (36 bytes)
> Mon Jul 24 15:06:25 2023 INVERTER: QPIWS: incorrect start/stop bytes.  Buffer: (100000000000001000000010000000010000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:30 2023 INVERTER: Current CRC: F8 54
> Mon Jul 24 15:06:30 2023 INVERTER: QPIRI reply size (97 bytes)
> Mon Jul 24 15:06:30 2023 INVERTER: QPIRI: incorrect start/stop bytes.  Buffer: (230.0 21.7 230.0 50.0 21.7 5000 5000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:30 2023 INVERTER: Current CRC: B4 DA
> Mon Jul 24 15:06:30 2023 INVERTER: QPIWS reply size (36 bytes)
> Mon Jul 24 15:06:30 2023 INVERTER: QPIWS: incorrect start/stop bytes.  Buffer: (100000000000001000000010000000010000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:35 2023 INVERTER: Current CRC: F8 54
> Mon Jul 24 15:06:36 2023 INVERTER: QPIRI reply size (97 bytes)
> Mon Jul 24 15:06:36 2023 INVERTER: QPIRI: incorrect start/stop bytes.  Buffer: (230.0 21.7 230.0 50.0 21.7 5000 5000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000
> Mon Jul 24 15:06:36 2023 INVERTER: Current CRC: B4 DA
> Mon Jul 24 15:06:36 2023 INVERTER: QPIWS reply size (36 bytes)
> Mon Jul 24 15:06:36 2023 INVERTER: QPIWS: incorrect start/stop bytes.  Buffer: (100000000000001000000010000000010000 48.0 46.0 42.0 56.4 54.0 0 030 060 1 0 0 9 01 0 0 54.0 0 1  00000 000

It should be noted that some query works, some not.

> root@Aspire-A315-31:/home/vizitnet/skymax-demo# ./inverter_poller -r QID
> Reply:  96332301102504
> root@Aspire-A315-31:/home/vizitnet/skymax-demo# ./inverter_poller -r QPIGS
> Reply:

**Comment by manio** [comment]
Is it working on https://github.com/ned-kelly/docker-voltronic-homeassistant and `inverter-cli` ?

**Comment by melnik-cto** [comment]
@manio sorry, forgot tu update this ticket. It was need to choose the buffer size for outgoing files. In my case with:
"QMOD", 5
"QPIGS", 110
"QPIRI", 105
"QPIWS", 40

With it values works fine.

And I found lots of forks where able set this value in inverter.conf (so no need to do cmake . && make after every change). It would be cool if you make a build where you could specify these values in the config - it's very convenient).
Thank you very much for your hard work. I would hang myself parsing console data from these inverters))
