### ISSUE TITLE
cant startup?

### ISSUE THREAD

**Issue by kxn25** [manio/skymax-demo#5]
Hello,
iam trying to connect my inverter to my Pi 3 b+.
so far i hava followed your instructions...
iam stuck at running `cmake . && make` 
Command not found!
 And how do i call `./ inverter_poller -h`

Iam looking for a way to get the inverter data into my iobroker.
There are somany programms and threads but i cant get i working :-(

**Comment by manio** [comment]
First you need some basic knowledge about compiling under linux.
Start with 'apt install build-essential cmake'

**Comment by kxn25** [comment]
Sorry for that did not know about cmake.
But thank you for your answer.
